Update patch set 2
Patch Set 2:

More symbols are still missing

packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:284: cannot find symbol
symbol  : variable Binder
location: class com.android.providers.userdictionary.UserDictionaryProvider
        final int callingUid = Binder.getCallingUid();
                               ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:285: cannot find symbol
symbol  : variable UserHandle
location: class com.android.providers.userdictionary.UserDictionaryProvider
        if (UserHandle.getAppId(callingUid) == Process.SYSTEM_UID
            ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:285: cannot find symbol
symbol  : variable SYSTEM_UID
location: class java.lang.Process
        if (UserHandle.getAppId(callingUid) == Process.SYSTEM_UID
                                                      ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:286: cannot find symbol
symbol  : variable ROOT_UID
location: class java.lang.Process
                || callingUid == Process.ROOT_UID
                                        ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:287: cannot find symbol
symbol  : method myUid()
location: class java.lang.Process
                || callingUid == Process.myUid()) {
                                        ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:291: cannot find symbol
symbol  : class List
location: class com.android.providers.userdictionary.UserDictionaryProvider
        List<InputMethodInfo> imeInfos = mImeManager.getEnabledInputMethodList();
        ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:291: cannot find symbol
symbol  : class InputMethodInfo
location: class com.android.providers.userdictionary.UserDictionaryProvider
        List<InputMethodInfo> imeInfos = mImeManager.getEnabledInputMethodList();
             ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:291: cannot find symbol
symbol  : variable mImeManager
location: class com.android.providers.userdictionary.UserDictionaryProvider
        List<InputMethodInfo> imeInfos = mImeManager.getEnabledInputMethodList();
                                         ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:295: cannot find symbol
symbol  : class InputMethodInfo
location: class com.android.providers.userdictionary.UserDictionaryProvider
                InputMethodInfo imeInfo = imeInfos.get(i);
                ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:302: cannot find symbol
symbol  : class SpellCheckerInfo
location: class com.android.providers.userdictionary.UserDictionaryProvider
        SpellCheckerInfo[] scInfos = mTextServiceManager.getEnabledSpellCheckers();
        ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:302: cannot find symbol
symbol  : variable mTextServiceManager
location: class com.android.providers.userdictionary.UserDictionaryProvider
        SpellCheckerInfo[] scInfos = mTextServiceManager.getEnabledSpellCheckers();
                                     ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:304: cannot find symbol
symbol  : class SpellCheckerInfo
location: class com.android.providers.userdictionary.UserDictionaryProvider
            for (SpellCheckerInfo scInfo : scInfos) {
                 ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:339: cannot find symbol
symbol  : method keyAt(int)
location: class java.util.HashMap<java.lang.String,java.lang.String>
                projection[i] = sDictProjectionMap.keyAt(i);
                                                  ^
packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:342: cannot find symbol
symbol  : class MatrixCursor
location: class com.android.providers.userdictionary.UserDictionaryProvider
        return new MatrixCursor(projection, 0);
                   ^
14 errors

Patch-set: 2