Update patch set 1
Patch Set 1:

I'm missing the following symbol:

packages/providers/UserDictionaryProvider/src/com/android/providers/userdictionary/UserDictionaryProvider.java:129: cannot find symbol
symbol  : method getEmptyCursorOrThrow(java.lang.String[])
location: class com.android.providers.userdictionary.UserDictionaryProvider
            return getEmptyCursorOrThrow(projection);

Patch-set: 1
CC: L R <12604@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>